import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const results=[];
try {
  const page=await browser.newPage({viewport:{width:1440,height:900}});
  await page.goto('http://127.0.0.1:3000',{waitUntil:'networkidle'});
  await page.locator('.hero-primary').click();await page.waitForTimeout(1400);
  assert(Math.abs(await page.locator('#projects').evaluate(e=>e.getBoundingClientRect().top)-78)<8);
  const card=page.locator('.project-card').first();await card.hover({position:{x:40,y:65}});await page.waitForTimeout(400);
  assert(await card.evaluate(e=>e.classList.contains('is-lit')));assert.notEqual(await card.evaluate(e=>getComputedStyle(e).rotate),'none');
  await page.screenshot({path:'qa/website/1440-card-hover.png'});
  await page.mouse.move(5,5);await page.waitForTimeout(350);assert.equal(await card.evaluate(e=>e.classList.contains('is-lit')),false);
  await page.locator('#journey').evaluate(el=>window.scrollTo({top:el.offsetTop-innerHeight*.6,behavior:'instant'}));await page.waitForTimeout(1400);
  const start=await page.locator('.journey-desktop > .absolute').evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).a);
  await page.evaluate(()=>window.scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'}));await page.waitForTimeout(1400);
  const end=await page.locator('.journey-desktop > .absolute').evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).a);
  assert(end>start);assert(end>.99);
  assert((await page.locator('header nav a[href="#contact"]').getAttribute('class')).includes('text-white'));
  results.push({desktop:'PASS',cursorGlow:'PASS',tilt:'PASS',heroAnchor:'PASS',journeyLine:{start,end},contactNavigation:'PASS'});
  const mobile=await browser.newPage({viewport:{width:390,height:844}});
  await mobile.goto('http://127.0.0.1:3000',{waitUntil:'networkidle'});
  await mobile.getByRole('button',{name:'Toggle navigation menu'}).click();
  await mobile.locator('header a[href="#skills"]').last().click();await mobile.waitForTimeout(1400);
  assert(Math.abs(await mobile.locator('#skills').evaluate(e=>e.getBoundingClientRect().top)-75)<8);
  results.push({mobileNavigation:'PASS'});
  const reduced=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});
  await reduced.goto('http://127.0.0.1:3000',{waitUntil:'networkidle'});
  assert(await reduced.evaluate(()=>[...document.querySelectorAll('.atmosphere-particle,.atmosphere-haze,.core-orbit-lines')].every(e=>getComputedStyle(e).animationName==='none')));
  assert.equal(await reduced.locator('.hero-photograph').evaluate(e=>getComputedStyle(e).transform),'none');
  results.push({reducedMotion:'PASS'});
  fs.writeFileSync('qa/website/interactions.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results));
} finally { await browser.close(); }
